# Generated by Django 4.2.19 on 2025-02-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
